# Configuration for Voxtral Real-time Streaming (FIXED)
server:
  host: "0.0.0.0"
  http_port: 8000
  health_port: 8005
  tcp_ports:
    - 8765
    - 8766
  
model:
  name: "mistralai/Voxtral-Mini-3B-2507"
  cache_dir: "./model_cache"
  device: "cuda"
  torch_dtype: "float16"  # OPTIMIZED: Use float16 for maximum GPU performance (faster than bfloat16)
  max_memory_per_gpu: "6GB"
  
audio:
  sample_rate: 16000
  chunk_size: 1024
  format: "int16"
  channels: 1
  frame_duration_ms: 30
  
# Mel spectrogram configuration matching Voxtral (FIXED)
spectrogram:
  n_mels: 128
  hop_length: 160
  win_length: 400
  n_fft: 1024  # FIXED: Increased to 1024 to fully resolve mel filterbank warning
  
streaming:
  max_connections: 100
  buffer_size: 4096
  timeout_seconds: 300
  latency_target_ms: 200

# TTS (Text-to-Speech) configuration - Kokoro TTS
tts:
  engine: "kokoro"
  default_voice: "hm_omega"  # Kokoro Hindi voice (replaces ऋतिका)
  sample_rate: 24000
  enabled: true
  # Kokoro TTS settings
  voice: "hm_omega"  # Kokoro Hindi voice
  speed: 1.0  # Kokoro speech speed
  lang_code: "h"  # Kokoro language code (h=Hindi, a=American English, b=British English)
  # Available voices by language - Kokoro voices only
  voices:
    english: ["af_heart", "af_bella", "af_nicole", "af_sarah"]  # Kokoro English voices
    hindi: ["hm_omega", "hf_alpha", "hf_beta", "hm_psi"]  # Kokoro Hindi voices
  # Performance settings
  performance:
    batch_size: 1  # Direct integration uses batch_size=1
    max_queue_size: 32
    num_workers: 4
    target_latency_ms: 150

# Speech-to-Speech pipeline configuration
speech_to_speech:
  enabled: true
  latency_target_ms: 300  # Updated to match <300ms requirement
  buffer_size: 8192
  output_format: "wav"
  quality: "high"
  emotional_expression: true
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/voxtral_streaming.log"
