# Configuration for Voxtral Real-time Streaming (FIXED)
server:
  host: "0.0.0.0"
  http_port: 8000
  health_port: 8005
  tcp_ports:
    - 8765
    - 8766
  
model:
  name: "mistralai/Voxtral-Mini-3B-2507"
  cache_dir: "./model_cache"
  device: "cuda"
  torch_dtype: "bfloat16"
  max_memory_per_gpu: "6GB"
  
audio:
  sample_rate: 16000
  chunk_size: 1024
  format: "int16"
  channels: 1
  frame_duration_ms: 30
  
# Mel spectrogram configuration matching Voxtral (FIXED)
spectrogram:
  n_mels: 128
  hop_length: 160
  win_length: 400
  n_fft: 1024  # FIXED: Increased to 1024 to fully resolve mel filterbank warning
  
streaming:
  max_connections: 100
  buffer_size: 4096
  timeout_seconds: 300
  latency_target_ms: 200

# TTS (Text-to-Speech) configuration
tts:
  engine: "orpheus"
  default_voice: "ऋतिका"  # Hindi voice as requested
  sample_rate: 24000
  enabled: true
  # LLM server configuration for Orpheus TTS
  llm_server:
    host: "localhost"
    port: 8010
    timeout: 30
  # Available voices by language
  voices:
    english: ["tara", "leah", "jess", "leo", "dan", "mia", "zac", "zoe"]
    french: ["pierre", "amelie", "marie"]
    german: ["jana", "thomas", "max"]
    korean: ["유나", "준서"]
    hindi: ["ऋतिका"]
    mandarin: ["长乐", "白芷"]
    spanish: ["javi", "sergio", "maria"]
    italian: ["pietro", "giulia", "carlo"]
  # Performance settings
  performance:
    batch_size: 16
    max_queue_size: 32
    num_workers: 4
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/voxtral_streaming.log"
