# Configuration for Voxtral Real-time Streaming (FIXED)
server:
  host: "0.0.0.0"
  http_port: 8000
  health_port: 8005
  tcp_ports:
    - 8765
    - 8766
  
model:
  name: "mistralai/Voxtral-Mini-3B-2507"
  cache_dir: "./model_cache"
  device: "cuda"
  torch_dtype: "bfloat16"
  max_memory_per_gpu: "6GB"
  
audio:
  sample_rate: 16000
  chunk_size: 1024
  format: "int16"
  channels: 1
  frame_duration_ms: 30
  
# Mel spectrogram configuration matching Voxtral (FIXED)
spectrogram:
  n_mels: 128
  hop_length: 160
  win_length: 400
  n_fft: 1024  # FIXED: Increased to 1024 to fully resolve mel filterbank warning
  
streaming:
  max_connections: 100
  buffer_size: 4096
  timeout_seconds: 300
  latency_target_ms: 200

# Kokoro TTS configuration for speech-to-speech
tts:
  model_name: "hexgrad/Kokoro-82M"
  cache_dir: "./model_cache/kokoro"
  device: "cuda"
  sample_rate: 24000
  voice: "af_heart"
  speed: 1.0
  lang_code: "a"  # American English
  emotional_expression: true

# Speech-to-Speech pipeline configuration
speech_to_speech:
  enabled: true
  latency_target_ms: 500
  buffer_size: 8192
  output_format: "wav"
  quality: "high"
  emotional_expression: true
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/voxtral_streaming.log"
